#!/usr/bin/env bash

apt-key adv --keyserver keyserver.ubuntu.com --recv 06E85760C0A52C50
#apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
echo "deb http://www.ubnt.com/downloads/unifi/debian unifi5 ubiquiti" >> /etc/apt/sources.list.d/100-ubnt.list
#echo "deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen" >> /etc/apt/sources.list.d./200-mongo.list
apt update
apt install unifi
apt-get autoclean
systemctl enable unifi
